name: pull-request-preview-teardown
on:
  pull_request:
    types: [closed]
jobs:
  veyoze-teardown:
    if: |
      github.event.pull_request.draft == false &&
      (
          (
              contains(github.event.pull_request.title, '[veyoze]') &&
              github.event.action == 'closed'
          ) ||
          (
              github.event.action == 'edited' &&
              contains(github.event.changes.title.from, '[veyoze]') &&
              !contains(github.event.pull_request.title, '[veyoze]')
          )
      )
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1
    steps:
      - name: Install Veyoze
        run: composer global require mehrancodes/veyoze -q
      - name: Start Teardown
        env:
          FORGE_TOKEN: ${{ secrets.FORGE_TOKEN }}
          FORGE_SERVER: ${{ secrets.FORGE_SERVER }}
          FORGE_GIT_REPOSITORY: ${{ github.repository }}
          FORGE_GIT_BRANCH: ${{ github.head_ref }}
          FORGE_DOMAIN: veyoze.com
        run: veyoze teardown
